version: '3.10'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 --access-logfile - --error-logfile - api.wsgi
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "80:8080"
    links:
      - db
    depends_on:
      - db