# Generated by Django 4.0.2 on 2022-02-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="description",
            field=models.TextField(
                blank=True, max_length=200, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.CharField(blank=True, max_length=50, verbose_name="nome"),
        ),
        migrations.AlterField(
            model_name="link",
            name="description",
            field=models.TextField(
                blank=True, max_length=200, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="name",
            field=models.CharField(blank=True, max_length=50, verbose_name="nome"),
        ),
    ]
