# Generated by Django 4.0.2 on 2022-02-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="activate_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="activate_expires",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_trusty",
        ),
    ]
